CREATE TABLE USUARIOS (
ID_USER INT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
SENHA VARCHAR(255) NOT NULL,
PRIMARY KEY (ID_USER)
);

CREATE TABLE FINANCEIRO (
ID_FNC INT NOT NULL AUTO_INCREMENT,
SALARIO INT,
ENTRADAS INT,
SAIDAS INT,
BALANCO INT,
FK_FNC_USER INT NOT NULL,
PRIMARY KEY (ID_FNC),
FOREIGN KEY (FK_FNC_USER) REFERENCES USUARIOS (ID_USER)
);